version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  banquito:
    build: .
    container_name: banquito
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin123@mongo:27017/banquito_turnos
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
